### ISSUE TITLE
Pipeline dies "No such variable: ch_transcriptome_sorted_bam"

### ISSUE THREAD

**Issue by julienlag** [Flomics/rnaseq#28]
### Description of the bug

Nextflow dies immediately after starting with this message. Please fix urgently and next time, run some basic tests before committing.

**Comment by lcabus-flomics** [comment]
I'm on it

**Comment by julienlag** [comment]
Can this be closed @lcabus-flomics ?

**Comment by lcabus-flomics** [comment]
Oh, I thought it closed upon the fixing of the bug in the pipeline, I close it now
