### ISSUE TITLE
Offer option to not publish big files

### ISSUE THREAD

**Issue by julienlag** [Flomics/rnaseq#30]
### Description of feature

For BAMs etc. 
Ideally, provide option "keepBams" with boolean value

**Comment by julienlag** [comment]
Also avoid publishing other intermediate files such as `umitools/*.fastq.gz`

**Comment by lcabus-flomics** [comment]
This is something that we can already avoid. We should change the config files, removing the line with save_umi_intermeds: true

**Comment by lcabus-flomics** [comment]
We should also remove the lines with:
save_align_intermeds: true
save_reference: true

**Comment by julienlag** [comment]
fantastic, thanks. I'm trying it now

**Comment by julienlag** [comment]
i guess this can be closed @lcabus-flomics ?

**Comment by lcabus-flomics** [comment]
@ctuni is doing some tests, since some of the bam files of the transcriptome were being published anyway. When she approves it, she can close it

**Comment by ctuni** [comment]
I created a `publish_bam` param which is turned off (false) by default. It's already on dev, I'll close this issue today!

**Comment by lcabus-flomics** [comment]
I can close this issue then, thanks Cristina!

**Comment by ctuni** [comment]
Should we publish bam files by default and let the users change the param to `false` if they are sure they do not want the files? @webermarcolivier

**Comment by julienlag** [comment]
I think that keeping the BAMs is only useful for debugging, so I would keep the default to false, what do people think?
