### ISSUE TITLE
skip PRESEQ_LCEXTRAP since it is not used

### ISSUE THREAD

**Issue by ctuni** [Flomics/rnaseq#51]
### Description of feature

This process (`NFCORE_RNASEQ:RNASEQ:PRESEQ_LCEXTRAP`) always fails and it is retried once for each fail and sample. Since it's not a "vital" process, the pipeline can continue with it failing, but we are not using it. This specific process, per the `preseq` manual, does the following:
"To predict the complexity curve of a sequencing library using an initial experiment in BED format, use the function lc_extrap. The required options are -o to specify the output of the yield estimates and the input file, which is either a BED file sorted by chromosome, start position, end position, and strand or a BAM file sorted with the samtools sort function."

For now, we do not need this feature and if we ever need it, I suggest we add a conditional case where this process is executed only if we input to the pipeline some type of BED file. What do you think?

**Comment by julienlag** [comment]
yes, I think it can be skipped, good idea

**Comment by ctuni** [comment]
Done in the params file: https://github.com/Flomics/nextflow-configs/blob/dev/rnaseq/Flomics_master_params.yml
